using otherId in OperationOutcome.issue.details
IHE/ITI.BasicAudit pull request #77
Opened 2023-06-21 17:00 UTC by oliveregger

This PR adds an example for OperationOutcome to indicate which HomeCommuntiyId the issue belongs to.

See background of discussion in https://groups.google.com/g/ititech/c/gdnPGG1TWrg/m/zyGSM69-AgAJ?utm_medium=email&utm_source=footer

The Extension ihe-otherId has been modified that OperationOutcome.issue.details is added as a possible context.

2023-06-21 20:26 UTC, JohnMoehrke commented
is there a way to profile OperationOutcome for this use?

Should we write some narrative to explain this OperationOutcome use? I am not clear where that text would go, as it seems out of scope of BALP. Is this OperationOutcome most likely to come from MHD when MHD is used as an API to multiple XCA communities? If so, should we add this narrative in the other.md, as new text to be added to MHD? Or is that something beyond what we want to say at this point?

2023-06-22 08:57 UTC, oliveregger commented
I would propose/offer to make a change proposal to MHD to illustrate the OperationOutcome with otherId when using it ans an API to multiple XCA communities. And we can also profile there OperationOutcome.

2023-06-22 11:54 UTC, JohnMoehrke commented
I just want something here that explains why this OperationOutcome exists. People will find it in the artifact list and wonder why it is here. They will wonder what it has to do with Audit Logging, and what is a homeCommunityId.

We could describe a federated set of Audit Record Repositories. Not as a formally accepted part of the profile, but as a systems design possibility.  We explain that each Audit Record Repository holds the audit logs for an XCA community, and thus the concept of a homeCommunityId is part of this systems design. Thus there is an Audit Consumer request to the Audit Record Repository federation, and it gets back partial success with the list of homeCommunityId that did not respond.

This would be best in some appendix. possibly 1:E?

The OperationOutcome needs to have narrative that explains it.

2023-07-24 19:54 UTC, JohnMoehrke commented
Seems you should use the HL7 extension http://hl7.org/fhir/extensions/StructureDefinition-artifact-identifier.html

2023-07-24 19:55 UTC, JohnMoehrke requested changes
use http://hl7.org/fhir/extensions/StructureDefinition-artifact-identifier.html
Then we don't need this change to BALP.

2023-10-06 12:33 UTC, oliveregger commented
following johns suggestion and closing this pr

2023-10-06 12:33 UTC, closed without merging